definitions:
  dto.AdminLoginInput:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  dto.ChangePWDInput:
    properties:
      originpassword:
        example: "123456"
        type: string
      password:
        example: "123456"
        type: string
    required:
    - originpassword
    - password
    type: object
  dto.ServiceAddHTTPInput:
    properties:
      black_list:
        description: 黑名单ip
        type: string
      clientip_flow_limit:
        description: 客户端ip限流
        type: integer
      header_transfor:
        description: header转换支持增加(add)、删除(del)、修改(edit) 格式：add headname headvalue
          多个逗号间隔
        type: string
      ip_list:
        description: ip列表
        type: string
      need_https:
        description: 是否支持HTTPS, 1=支持
        type: integer
      need_strip_uri:
        description: 是否启用strip_uri, 1=启用
        type: integer
      need_websocket:
        description: 是否支持websocket, 1=支持
        type: integer
      open_auth:
        description: 是否开启权限 1=开启
        type: integer
      round_type:
        description: 轮询方式 0=random 1=round_robin 2=wieght_round_robin 3=ip_hash
        type: integer
      rule:
        description: 接入路径
        type: string
      rule_type:
        description: 接入类型
        type: integer
      serbice_desc:
        description: 服务描述
        type: string
      service_flow_limit:
        description: 服务器限流
        type: integer
      service_name:
        description: 服务名称
        type: string
      upstream_connect_timeout:
        description: 建立连接超时，单位s
        type: integer
      upstream_header_timeout:
        description: 获取header超时，单位s
        type: integer
      upstream_idle_timeout:
        description: 链接最大空闲时间，单位s
        type: integer
      upstream_max_idle:
        description: 最大空闲链接数
        type: integer
      url_rewrite:
        description: url重写功能 格式：^/gatekeeper/test_service(.*) $1 多个逗号间隔
        type: string
      weight_list:
        description: 权重列表
        type: string
      white_list:
        description: 白名单ip
        type: string
    required:
    - ip_list
    - rule
    - serbice_desc
    - service_name
    - weight_list
    type: object
  middleware.Response:
    properties:
      data:
        type: object
      errmsg:
        type: string
      errno:
        type: integer
      stack:
        type: object
      trace_id:
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /admin_info/changepwd:
    post:
      consumes:
      - application/json
      description: 管理员密码修改
      operationId: /admin_info/changepwd
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePWDInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 管理员密码修改
      tags:
      - 管理员接口
  /admin_info/info:
    get:
      consumes:
      - application/json
      description: 管理员信息
      operationId: /admin_info/info
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 管理员信息
      tags:
      - 管理员接口
  /admin_login/login:
    post:
      consumes:
      - application/json
      description: 管理员登录
      operationId: /admin_login/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 管理员登录
      tags:
      - 管理员接口
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: 管理员退出
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 管理员退出
      tags:
      - 管理员接口
  /service/service_add_http:
    post:
      consumes:
      - application/json
      description: 添加HTTP服务
      operationId: /service/service_add_http
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ServiceAddHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 添加HTTP服务
      tags:
      - 服务管理
  /service/service_delete:
    get:
      consumes:
      - application/json
      description: 服务删除
      operationId: /service/service_delete
      parameters:
      - description: 服务ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 服务删除
      tags:
      - 服务管理
  /service/service_list:
    get:
      consumes:
      - application/json
      description: 服务列表
      operationId: /service/service_list
      parameters:
      - description: 关键词
        in: query
        name: info
        type: string
      - description: 页数
        in: query
        name: page_no
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 服务列表
      tags:
      - 服务管理
swagger: "2.0"
